# Generated by Django 3.0.6 on 2020-10-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('period_play', models.CharField(max_length=2000)),
                ('description', models.TextField(max_length=200000)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
